name: "Internal release (auth)"

on:
    workflow_dispatch: # Allow manually running the action

env:
    FLUTTER_VERSION: "3.24.3"

permissions:
    contents: write

jobs:
    build:
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: auth

        steps:
            - name: Checkout code and submodules
              uses: actions/checkout@v4
              with:
                  submodules: recursive

            - name: Setup JDK 17
              uses: actions/setup-java@v1
              with:
                  java-version: 17

            - name: Install Flutter ${{ env.FLUTTER_VERSION  }}
              uses: subosito/flutter-action@v2
              with:
                  channel: "stable"
                  flutter-version: ${{ env.FLUTTER_VERSION  }}
                  cache: true

            # - name: Setup keys
            #   uses: timheuer/base64-to-file@v1
            #   with:
            #       fileName: "keystore/ente_auth_key.jks" # Changed for auth
            #       encodedString: ${{ secrets.SIGNING_KEY_AUTH }} # Changed for auth

            - name: Build independent APK (Debug)
              run: |
                  flutter build apk --dart-define=cronetHttpNoPlay=true --debug --flavor independent
                  mkdir -p artifacts
                  mv build/app/outputs/flutter-apk/app-independent-debug.apk artifacts/ente-auth-debug.apk # Changed to a fixed name

            # - name: Build PlayStore AAB
            #   run: |
            #       flutter build appbundle --dart-define=cronetHttpNoPlay=true --release --flavor playstore
            #   env:
            #       SIGNING_KEY_PATH: "/home/runner/work/_temp/keystore/ente_auth_key.jks" # Changed for auth
            #       SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS_AUTH }} # Changed for auth
            #       SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD_AUTH }} # Changed for auth
            #       SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD_AUTH }} # Changed for auth

            - name: Upload Debug APK to Release
              uses: softprops/action-gh-release@v2
              with:
                files: auth/artifacts/ente-auth-debug.apk
                tag_name: auth-debug-run-${{ github.run_id }} # Creates a unique tag for this run
                name: "Auth Debug Build (Run ${{ github.run_id }})"
                body: |
                  Internal debug build of the Ente Auth application.
                  Triggered from ref: ${{ github.ref }}
                  Workflow Run ID: ${{ github.run_id }}
                  Workflow Run Number: ${{ github.run_number }}
                draft: false
                prerelease: true # Mark as pre-release
